nginx:
  container_name: nginx_neo
  image: neo1seok/nginx
  #  name: nginx_neo
  ports:
    - "8883:80"
  volumes:
    - /srv/docker/nginx/nginx.conf:/etc/nginx/nginx_.conf
    - .:/home/nginx  

  restart: always

